---
- apt_key:
    state: present
    url: http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- apt_repository:
    repo: "deb http://packages.elasticsearch.org/elasticsearch/{{ elasticsearch_version | regex_replace('(\\.\\d+)$', '') }}/debian stable main "
    state: present
    update_cache: yes

- apt:
    pkg: "elasticsearch={{ elasticsearch_version }}"

- name: setup elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart elasticsearch

- name: setup elasticsearch defaults
  template:
    src: elasticsearch.defaults.j2
    dest: "/etc/default/elasticsearch"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart elasticsearch

- service:
    name: elasticsearch
    state: started
