---
- name: download elasticsearch
  get_url:
    url: "https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.deb"

- name: install elasticsearch
  command: "dpkg -i /tmp/elasticsearch-{{ elasticsearch_version }}.deb"

- name: setup basic_auth
  template:
    src: elasticsearch.js
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart elasticsearch

- service:
    name: elasticsearch
    state: started
